0.2.1: Make it build with git.

diff --git a/include/Makefile.am b/include/Makefile.am
--- a/include/Makefile.am
+++ b/include/Makefile.am
@@ -1,20 +1,22 @@
-BUILT_SOURCES = package-version.h build-info.h
-CLEANFILES = $(BUILT_SOURCES)
+BUILT_SOURCES = git-version.stamp build-info.stamp
+CLEANFILES = $(BUILT_SOURCES) git-version.h build-info.h
 
-package-version.h: $(top_srcdir)/ChangeLog Makefile
-	TLA_ARCHIVE="$$(grep -E "^#.*arch-tag: " $<  | sed -e 's/^.*automatic-ChangeLog--//g' -e 's/\/.*$$//g')"; \
-	TLA_REV="$$(grep -E -A1 -m1 '^[[:space:]]*Revision:$$' $< | awk '(NR == 2) { print $$1; }')"; \
-	TLA_REVISION="$${TLA_ARCHIVE}/$${TLA_REV}"; \
-	for var in TLA_REVISION; do \
-		export var; \
-		echo "#define $$var \"$$(eval echo "\$$$$var")\""; \
-	done > "$@"
+GIT_VERSION_CMD = $(SHELL) $(top_srcdir)/git-version.sh
+git-version.stamp:
+	env GIT_DIR="$(top_srcdir)/.git" $(GIT_VERSION_CMD) -s $(top_srcdir) -o git-version.h
+	@if test -s "$(srcdir)/git-version.h"; then \
+		if cmp "$(srcdir)/git-version.h" "git-version.h"; then :; \
+		else \
+			echo "Error: $(srcdir)/git-version.h and git-version.h differ."; \
+			echo "       You probably want to remove the former."; \
+			exit 1; \
+		fi; \
+	fi
 
-.PHONY: build-info.h
-build-info.h:
+build-info.stamp:
 	BUILD_DATE="$$(TZ=UTC date)"; \
 	DATE_YEAR="$$(TZ=UTC date '+%Y')"; \
 	for var in BUILD_DATE DATE_YEAR; do \
 		export var; \
 		echo "#define $$var \"$$(eval echo "\$$$$var")\""; \
-	done > "$@"
+	done > "build-info.h"
