Make sure ARCH_REVISION is set for sending logs
git-archimport-id: hun@n-dimensional.de--2004-public/ndim-utils--main--0.1--patch-40

diff --git a/tla/commit-sendlog b/tla/commit-sendlog
--- a/tla/commit-sendlog
+++ b/tla/commit-sendlog
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ "$ARCH_REVISION" = "" ]; then
+    echo "$0 called without ARCH_REVISION set. Aborting."
+    exit 1
+fi
+
 arch_summary_domain="arch.n-dimensional.de"
 email="${ARCH_ONLY_CATEGORY}-summary@${arch_summary_domain}"
 
